<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%biaya}}".
 *
 * @property integer $replid
 * @property string $biaya
 * @property string $kode
 * @property integer $isAngsur
 * @property integer $isDiskon
 * @property string $ditagih
 * @property string $keterangan
 *
 * @property KeuRekeningbiaya[] $keuRekeningbiayas
 */
class Biaya extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%biaya}}';
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if($insert){
            $this->generateDetilBiaya();
        }
    }

    private function generateDetilBiaya()
    {
        $departemenModel = Departemen::find();
        $subTingkatModel = Subtingkat::find();
        $golonganModel = GolonganSiswa::find();
        $detailBiaya = [];
        foreach ($departemenModel->all() as $departemen){
            foreach ($subTingkatModel->all() as $subtingkat){
                foreach ($golonganModel->all() as $golonganSiswa){
                    $detailBiaya[] = [$this->replid,$subtingkat->replid,$golonganSiswa->id,0,0];
                }
            }
        }
        $command = Yii::$app->db->createCommand();
        $command->batchInsert(DetailBiaya::tableName(),['biaya','subtingkat','golongan','nominal','detilrekening'],$detailBiaya)->execute();
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['biaya', 'kode'], 'required'],
            [['isAngsur', 'isDiskon'], 'integer'],
            [['ditagih', 'keterangan'], 'string'],
            [['biaya'], 'string', 'max' => 100],
            [['kode'], 'string', 'max' => 50],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'replid' => Yii::t('app', 'Replid'),
            'biaya' => Yii::t('app', 'Biaya'),
            'kode' => Yii::t('app', 'Kode'),
            'isAngsur' => Yii::t('app', 'Is Angsur'),
            'isDiskon' => Yii::t('app', 'Is Diskon'),
            'ditagih' => Yii::t('app', 'Ditagih'),
            'keterangan' => Yii::t('app', 'Keterangan'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeuRekeningbiayas()
    {
        return $this->hasMany(KeuRekeningbiaya::className(), ['biaya' => 'replid']);
    }
}
