<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%keu_detilrekening}}".
 *
 * @property integer $replid
 * @property integer $kategorirekening
 * @property string $kode
 * @property string $nama
 * @property string $keterangan
 *
 * @property KategoriRekening $idKatRekening
 * @property Saldorekening[] $keuSaldorekenings
 */
class Detilrekening extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%keu_detilrekening}}';
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        if($insert){
            $tahunAjaran = TahunAjaran::find();
            $command = Yii::$app->db->createCommand();
            $listSaldo = [];
            foreach ($tahunAjaran->all() as $item){
                $listSaldo[] =[$this->replid,$item->id];
            }
            $command->batchInsert(Saldorekening::tableName(),['detilrekening','tahunajaran'],$listSaldo);
            $command->execute();
        }
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kategorirekening', 'kode', 'nama', 'keterangan'], 'required'],
            [['kode'],'unique'],
            [['kategorirekening'], 'integer'],
            [['kode'], 'string', 'max' => 20],
            [['nama'], 'string', 'max' => 100],
            [['keterangan'], 'string', 'max' => 200],
            [['kategorirekening'], 'exist', 'skipOnError' => true, 'targetClass' => KategoriRekening::className(), 'targetAttribute' => ['kategorirekening' => 'replid']],

        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'replid' => Yii::t('app', 'Replid'),
            'kategorirekening' => Yii::t('app', 'Kategori Rekening'),
            'kode' => Yii::t('app', 'Kode'),
            'nama' => Yii::t('app', 'Nama'),
            'keterangan' => Yii::t('app', 'Keterangan'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdKatRekening()
    {
        return $this->hasOne(KategoriRekening::className(), ['replid' => 'kategorirekening']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKeuSaldorekenings()
    {
        return $this->hasMany(Saldorekening::className(), ['detilrekening' => 'replid']);
    }

    /**
     * @inheritdoc
     * @return DetilrekeningQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new DetilrekeningQuery(get_called_class());
    }
}
