<?php

namespace app\models;

use Yii;
use yii\db\Query;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "{{%subtingkat}}".
 *
 * @property integer $replid
 * @property string $subtingkat
 * @property integer $tingkat
 * @property integer $urutan
 * @property string $keterangan
 * @property Tingkat $idTingkat
 *
 */
class Subtingkat extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%subtingkat}}';
    }
    
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        if($insert){

        }
    }

    private function generateDetailBiaya()
    {
        $command = Yii::$app->db->createCommand();


        $command->batchInsert('psb_detailbiaya',['biaya','subtingkat','detailgelombang','golongan'],$list);
    }
    

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['subtingkat', 'tingkat', 'urutan', 'keterangan'], 'required'],
            [['tingkat', 'urutan'], 'integer'],
            [['keterangan'], 'string'],
            [['subtingkat'], 'string', 'max' => 100],
        ];
    }

    public function getIdTingkat()
    {
        return $this->hasOne(Tingkat::className(),['id' => 'tingkat']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'replid' => Yii::t('app', 'Replid'),
            'subtingkat' => Yii::t('app', 'Subtingkat'),
            'tingkat' => Yii::t('app', 'Tingkat'),
            'urutan' => Yii::t('app', 'Urutan'),
            'keterangan' => Yii::t('app', 'Keterangan'),
        ];
    }

    public static function selectOptions()
    {
        $model = self::find()->orderBy(['urutan' => SORT_ASC])->all();
        return ArrayHelper::map($model,'replid','keterangan');
    }
}
